version: "3.9"
services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000" # Expose Next.js on localhost:3000
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: your_user
      DATABASE_PASSWORD: your_password
      DATABASE_PORT: 5432
      DATABASE_NAME: file_uploader
    depends_on:
      - postgres # Ensure PostgreSQL starts first

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: file_uploader
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

